<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->
<!DOCTYPE cis-element-search[
<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>
<!ELEMENT program-name (#PCDATA)>
<!ELEMENT parameters (
  pattern-file, 
  sequence-file, 
  background-seq-file?,
  pattern-pvalue-cutoff?,
  sequence-pvalue-cutoff?,
  site-pvalue-cutoff?,
  sequence-filtering,
  ANY*
 )>
<!ELEMENT command-line (#PCDATA)>
<!ELEMENT pattern-file (#PCDATA)>
<!ELEMENT sequence-file (#PCDATA)>
<!ELEMENT background-seq-file (#PCDATA)>
<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>
<!ELEMENT site-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-filtering EMPTY>
<!ELEMENT multi-pattern-scan (pattern+, ANY*)>
<!ELEMENT pattern (scanned-sequence+, ANY*)>
<!ELEMENT scanned-sequence (matched-element*, ANY*)>
<!ELEMENT matched-element (sequence)>
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST cis-element-search
xmlns:xsi CDATA #IMPLIED
xmlns:mem CDATA #IMPLIED
xsi:schemaLocation CDATA #IMPLIED
>
<!ATTLIST sequence-filtering
on-off CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ATTLIST multi-pattern-scan
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
>
<!ATTLIST pattern
accession CDATA #REQUIRED
name CDATA #REQUIRED
pvalue CDATA #IMPLIED
score CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST scanned-sequence
accession CDATA #REQUIRED
name CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
length CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST matched-element
start CDATA #REQUIRED
stop CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
clusterid CDATA #IMPLIED
>

]>
<cis-element-search
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://zlab.bu.edu/schema/cisml cisml.xsd"
  xmlns="http://zlab.bu.edu/schema/cisml"
  xmlns:mem="http://noble.gs.washington.edu/meme"
>
<program-name>fimo</program-name>
<parameters>
<command-line>fimo --parse-genomic-coord --verbosity 1 --oc /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/fimo_out_7 --bgfile /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/background --motif GGGGCGGGGCC /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/meme_out/meme.xml /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/human_promoter.fa</command-line>
<pattern-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/meme_out/meme.xml</pattern-file>
<sequence-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/human_promoter.fa</sequence-file>
<site-pvalue-cutoff>0.0001</site-pvalue-cutoff>
<sequence-filtering on-off="off"/>
</parameters>
<pattern accession="GGGGCGGGGCC" name="MEME-6">
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="9700560" stop="9700570" score="15.127" pvalue="6.19e-06">
<sequence>ggggcggggcg</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
<matched-element start="9700487" stop="9700497" score="13.6349" pvalue="2.02e-05">
<sequence>agggcggggcc</sequence>
<mem:qvalue>0.0657</mem:qvalue>
</matched-element>
<matched-element start="9700555" stop="9700565" score="13.0794" pvalue="3.03e-05">
<sequence>ggggaggggcg</sequence>
<mem:qvalue>0.0766</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="10039725" stop="10039735" score="16.1905" pvalue="2.36e-06">
<sequence>ggggcggggcc</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21079242" stop="21079232" score="16.1905" pvalue="2.36e-06">
<sequence>GGGGCGGGGCC</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
<matched-element start="21079264" stop="21079254" score="15.127" pvalue="6.19e-06">
<sequence>GGGGCGGGGCG</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="23383195" stop="23383205" score="12.6349" pvalue="3.75e-05">
<sequence>ggggaggagcc</sequence>
<mem:qvalue>0.0856</mem:qvalue>
</matched-element>
<matched-element start="23383267" stop="23383257" score="12.5714" pvalue="3.99e-05">
<sequence>AGGGCGGGGCG</sequence>
<mem:qvalue>0.0873</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="24100339" stop="24100329" score="16.1905" pvalue="2.36e-06">
<sequence>GGGGCGGGGCC</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="30873426" stop="30873436" score="15.127" pvalue="6.19e-06">
<sequence>ggggcggggcg</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
<matched-element start="30873431" stop="30873441" score="15.127" pvalue="6.19e-06">
<sequence>ggggcggggcg</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="32172677" stop="32172667" score="12.5714" pvalue="3.99e-05">
<sequence>AGGGCGGGGCG</sequence>
<mem:qvalue>0.0873</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="33720035" stop="33720045" score="12.6349" pvalue="3.75e-05">
<sequence>GGGGAGGAGCC</sequence>
<mem:qvalue>0.0856</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="33907896" stop="33907886" score="10.254" pvalue="9.87e-05">
<sequence>GGGGCGGGACG</sequence>
<mem:qvalue>0.138</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="34236575" stop="34236585" score="11.0635" pvalue="7.64e-05">
<sequence>AGGGCGGAGCG</sequence>
<mem:qvalue>0.124</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="34678139" stop="34678149" score="15.127" pvalue="6.19e-06">
<sequence>GGGGCGGGGCG</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="36068241" stop="36068231" score="16.1905" pvalue="2.36e-06">
<sequence>GGGGCGGGGCC</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
<matched-element start="36068246" stop="36068236" score="13.0794" pvalue="3.03e-05">
<sequence>GGGGAGGGGCG</sequence>
<mem:qvalue>0.0766</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37029243" stop="37029253" score="15.0159" pvalue="7.66e-06">
<sequence>TGGGCGGGGCC</sequence>
<mem:qvalue>0.0398</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37541049" stop="37541039" score="12.5714" pvalue="3.99e-05">
<sequence>AGGGCGGGGCG</sequence>
<mem:qvalue>0.0873</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37864930" stop="37864920" score="16.1905" pvalue="2.36e-06">
<sequence>GGGGCGGGGCC</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
<matched-element start="37865009" stop="37864999" score="12.5714" pvalue="3.99e-05">
<sequence>AGGGCGGGGCG</sequence>
<mem:qvalue>0.0873</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="38129670" stop="38129660" score="14.254" pvalue="1.24e-05">
<sequence>GGGGCGGAGCT</sequence>
<mem:qvalue>0.05</mem:qvalue>
</matched-element>
<matched-element start="38129675" stop="38129665" score="13.0794" pvalue="3.03e-05">
<sequence>GGGGAGGGGCG</sequence>
<mem:qvalue>0.0766</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="38987735" stop="38987725" score="12.127" pvalue="4.91e-05">
<sequence>AGGGCGGAGCC</sequence>
<mem:qvalue>0.0992</mem:qvalue>
</matched-element>
<matched-element start="38987747" stop="38987757" score="11.7937" pvalue="5.54e-05">
<sequence>GGGGCGGGGAG</sequence>
<mem:qvalue>0.105</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="39367779" stop="39367769" score="13.619" pvalue="2.16e-05">
<sequence>GGGGCGGAGCG</sequence>
<mem:qvalue>0.0676</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="40681537" stop="40681527" score="15.127" pvalue="6.19e-06">
<sequence>GGGGCGGGGCG</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
<matched-element start="40681542" stop="40681532" score="15.127" pvalue="6.19e-06">
<sequence>GGGGCGGGGCG</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="42851185" stop="42851175" score="12.3492" pvalue="4.28e-05">
<sequence>GGGGCGGAGTT</sequence>
<mem:qvalue>0.0916</mem:qvalue>
</matched-element>
<matched-element start="42851255" stop="42851245" score="12.2381" pvalue="4.61e-05">
<sequence>GGGGTGGAGCC</sequence>
<mem:qvalue>0.0966</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="42953070" stop="42953060" score="14.1429" pvalue="1.39e-05">
<sequence>GGGGAGGGGCC</sequence>
<mem:qvalue>0.054</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="43163749" stop="43163739" score="11.3492" pvalue="6.62e-05">
<sequence>GGGGCGGAGAC</sequence>
<mem:qvalue>0.115</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="43933986" stop="43933976" score="14.6825" pvalue="9.13e-06">
<sequence>GGGGCGGAGCC</sequence>
<mem:qvalue>0.0426</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="45925618" stop="45925628" score="14.254" pvalue="1.24e-05">
<sequence>GGGGCGGAGCT</sequence>
<mem:qvalue>0.05</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="51915142" stop="51915132" score="15.7619" pvalue="3.83e-06">
<sequence>GGGGCGGGGCT</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="52500442" stop="52500432" score="10.5238" pvalue="9.03e-05">
<sequence>AGGGAGGGGCG</sequence>
<mem:qvalue>0.133</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="52630691" stop="52630681" score="14.6825" pvalue="9.13e-06">
<sequence>GGGGCGGAGCC</sequence>
<mem:qvalue>0.0426</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="52817477" stop="52817487" score="11.1746" pvalue="7.28e-05">
<sequence>GGGGAGGGGTG</sequence>
<mem:qvalue>0.121</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="52952743" stop="52952753" score="13.6349" pvalue="2.02e-05">
<sequence>AGGGCGGGGCC</sequence>
<mem:qvalue>0.0657</mem:qvalue>
</matched-element>
<matched-element start="52952862" stop="52952852" score="12.6349" pvalue="3.75e-05">
<sequence>GGGGAGGAGCC</sequence>
<mem:qvalue>0.0856</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="55131201" stop="55131191" score="13.0794" pvalue="3.03e-05">
<sequence>GGGGAGGGGCG</sequence>
<mem:qvalue>0.0766</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="55406158" stop="55406148" score="11.7937" pvalue="5.54e-05">
<sequence>GGGGCGGGGAG</sequence>
<mem:qvalue>0.105</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="56972987" stop="56972977" score="10.2857" pvalue="9.72e-05">
<sequence>GGGGCGGAGAG</sequence>
<mem:qvalue>0.137</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="56977266" stop="56977256" score="11.6825" pvalue="5.93e-05">
<sequence>TGGGCGGGGAC</sequence>
<mem:qvalue>0.109</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="58424071" stop="58424081" score="15.0159" pvalue="7.66e-06">
<sequence>TGGGCGGGGCC</sequence>
<mem:qvalue>0.0398</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="58973594" stop="58973604" score="13.619" pvalue="2.16e-05">
<sequence>GGGGCGGAGCG</sequence>
<mem:qvalue>0.0676</mem:qvalue>
</matched-element>
<matched-element start="58973623" stop="58973633" score="12.6825" pvalue="3.66e-05">
<sequence>GGGGTGGGGCG</sequence>
<mem:qvalue>0.0853</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="59481920" stop="59481910" score="13.0794" pvalue="3.03e-05">
<sequence>GGGGAGGGGCG</sequence>
<mem:qvalue>0.0766</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="59763503" stop="59763513" score="15.127" pvalue="6.19e-06">
<sequence>ggggcggggcg</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="60180436" stop="60180446" score="13.7143" pvalue="1.87e-05">
<sequence>GGGGAGGGGCT</sequence>
<mem:qvalue>0.0648</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="60566815" stop="60566825" score="14.5873" pvalue="1e-05">
<sequence>TGGGCGGGGCT</sequence>
<mem:qvalue>0.0443</mem:qvalue>
</matched-element>
<matched-element start="60566749" stop="60566759" score="13.9524" pvalue="1.54e-05">
<sequence>TGGGCGGGGCG</sequence>
<mem:qvalue>0.057</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="64119894" stop="64119884" score="15.127" pvalue="6.19e-06">
<sequence>GGGGCGGGGCG</sequence>
<mem:qvalue>0.0362</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="64690888" stop="64690878" score="10.4127" pvalue="9.18e-05">
<sequence>GGGGTGGGGAC</sequence>
<mem:qvalue>0.133</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="64737799" stop="64737789" score="16.1905" pvalue="2.36e-06">
<sequence>GGGGCGGGGCC</sequence>
<mem:qvalue>0.0352</mem:qvalue>
</matched-element>
<matched-element start="64737876" stop="64737866" score="11.6825" pvalue="5.93e-05">
<sequence>TGGGCGGGGAC</sequence>
<mem:qvalue>0.109</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="64956588" stop="64956578" score="10.619" pvalue="8.88e-05">
<sequence>TGGGCGGGGAG</sequence>
<mem:qvalue>0.131</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="71557091" stop="71557081" score="13.9524" pvalue="1.54e-05">
<sequence>TGGGCGGGGCG</sequence>
<mem:qvalue>0.057</mem:qvalue>
</matched-element>
<matched-element start="71557130" stop="71557140" score="11.3175" pvalue="6.77e-05">
<sequence>GGGGCGGGACC</sequence>
<mem:qvalue>0.115</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="72284325" stop="72284315" score="14.2857" pvalue="1.15e-05">
<sequence>GGGGCGGGGTC</sequence>
<mem:qvalue>0.0482</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>