<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->
<!DOCTYPE cis-element-search[
<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>
<!ELEMENT program-name (#PCDATA)>
<!ELEMENT parameters (
  pattern-file, 
  sequence-file, 
  background-seq-file?,
  pattern-pvalue-cutoff?,
  sequence-pvalue-cutoff?,
  site-pvalue-cutoff?,
  sequence-filtering,
  ANY*
 )>
<!ELEMENT command-line (#PCDATA)>
<!ELEMENT pattern-file (#PCDATA)>
<!ELEMENT sequence-file (#PCDATA)>
<!ELEMENT background-seq-file (#PCDATA)>
<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>
<!ELEMENT site-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-filtering EMPTY>
<!ELEMENT multi-pattern-scan (pattern+, ANY*)>
<!ELEMENT pattern (scanned-sequence+, ANY*)>
<!ELEMENT scanned-sequence (matched-element*, ANY*)>
<!ELEMENT matched-element (sequence)>
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST cis-element-search
xmlns:xsi CDATA #IMPLIED
xmlns:mem CDATA #IMPLIED
xsi:schemaLocation CDATA #IMPLIED
>
<!ATTLIST sequence-filtering
on-off CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ATTLIST multi-pattern-scan
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
>
<!ATTLIST pattern
accession CDATA #REQUIRED
name CDATA #REQUIRED
pvalue CDATA #IMPLIED
score CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST scanned-sequence
accession CDATA #REQUIRED
name CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
length CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST matched-element
start CDATA #REQUIRED
stop CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
clusterid CDATA #IMPLIED
>

]>
<cis-element-search
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://zlab.bu.edu/schema/cisml cisml.xsd"
  xmlns="http://zlab.bu.edu/schema/cisml"
  xmlns:mem="http://noble.gs.washington.edu/meme"
>
<program-name>fimo</program-name>
<parameters>
<command-line>fimo --parse-genomic-coord --verbosity 1 --oc /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/fimo_out_11 --bgfile /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/background --motif 10-GCTCACAACCATCTGTAA /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/streme_out/streme.xml /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/mouse_enhancer.fa</command-line>
<pattern-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/streme_out/streme.xml</pattern-file>
<sequence-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_mouse_enhancer/mouse_enhancer.fa</sequence-file>
<site-pvalue-cutoff>0.0001</site-pvalue-cutoff>
<sequence-filtering on-off="off"/>
</parameters>
<pattern accession="10-GCTCACAACCATCTGTAA" name="STREME-10">
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="4426844" stop="4426861" score="7.79518" pvalue="3.52e-05">
<sequence>TCTCTCTGCCATCTAAAA</sequence>
<mem:qvalue>0.421</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="8872845" stop="8872862" score="10.3614" pvalue="1.19e-05">
<sequence>actcacaattatctcttc</sequence>
<mem:qvalue>0.24</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="9585020" stop="9585003" score="7.60241" pvalue="3.81e-05">
<sequence>GCTCACAAACATGGTTAT</sequence>
<mem:qvalue>0.437</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="13699781" stop="13699798" score="10.1687" pvalue="1.29e-05">
<sequence>actcatgattatccctaa</sequence>
<mem:qvalue>0.251</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="16172567" stop="16172584" score="6.20482" pvalue="6.63e-05">
<sequence>GCTCCCAAGCTCTTGTGA</sequence>
<mem:qvalue>0.529</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="16250013" stop="16250030" score="5.78313" pvalue="7.8e-05">
<sequence>GCACAGTGTCATCTCTAA</sequence>
<mem:qvalue>0.556</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21059826" stop="21059843" score="7.28916" pvalue="4.32e-05">
<sequence>ACTCAGATCCATCCGAGA</sequence>
<mem:qvalue>0.454</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21101290" stop="21101273" score="6.96386" pvalue="4.92e-05">
<sequence>AGCCACAACCATGTGTGA</sequence>
<mem:qvalue>0.481</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21220972" stop="21220955" score="14.6867" pvalue="1.56e-06">
<sequence>GCTCACAACTGCCCGAGA</sequence>
<mem:qvalue>0.0548</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21266984" stop="21266967" score="28.506" pvalue="1.33e-10">
<sequence>GCTCACAATCATCTGTAA</sequence>
<mem:qvalue>3.99e-05</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="21531033" stop="21531016" score="7.39759" pvalue="4.14e-05">
<sequence>GTTCATGCCCTTCTGTGA</sequence>
<mem:qvalue>0.45</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="31153134" stop="31153151" score="6.10843" pvalue="6.88e-05">
<sequence>GTTCACAACAATGTCTGG</sequence>
<mem:qvalue>0.535</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="33672718" stop="33672701" score="6.28916" pvalue="6.41e-05">
<sequence>AATTACAGCAGCCTGTAA</sequence>
<mem:qvalue>0.525</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="34867393" stop="34867376" score="18.3494" pvalue="2.2e-07">
<sequence>GCTCACAACTGCCCTTAA</sequence>
<mem:qvalue>0.0109</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="34897041" stop="34897058" score="9.04819" pvalue="2.09e-05">
<sequence>gcacacagtcatgtgtag</sequence>
<mem:qvalue>0.328</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37041114" stop="37041097" score="6.45783" pvalue="6e-05">
<sequence>TCTCAGAGACATCTTTAG</sequence>
<mem:qvalue>0.516</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37272569" stop="37272586" score="8.48193" pvalue="2.66e-05">
<sequence>GCTCAGAGCCACAGGAAA</sequence>
<mem:qvalue>0.371</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37634809" stop="37634826" score="28.2169" pvalue="2.21e-10">
<sequence>gctcacgaccatctgtaa</sequence>
<mem:qvalue>5.44e-05</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="39068021" stop="39068004" score="6.14458" pvalue="6.78e-05">