<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->
<!DOCTYPE cis-element-search[
<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>
<!ELEMENT program-name (#PCDATA)>
<!ELEMENT parameters (
  pattern-file, 
  sequence-file, 
  background-seq-file?,
  pattern-pvalue-cutoff?,
  sequence-pvalue-cutoff?,
  site-pvalue-cutoff?,
  sequence-filtering,
  ANY*
 )>
<!ELEMENT command-line (#PCDATA)>
<!ELEMENT pattern-file (#PCDATA)>
<!ELEMENT sequence-file (#PCDATA)>
<!ELEMENT background-seq-file (#PCDATA)>
<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>
<!ELEMENT site-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-filtering EMPTY>
<!ELEMENT multi-pattern-scan (pattern+, ANY*)>
<!ELEMENT pattern (scanned-sequence+, ANY*)>
<!ELEMENT scanned-sequence (matched-element*, ANY*)>
<!ELEMENT matched-element (sequence)>
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST cis-element-search
xmlns:xsi CDATA #IMPLIED
xmlns:mem CDATA #IMPLIED
xsi:schemaLocation CDATA #IMPLIED
>
<!ATTLIST sequence-filtering
on-off CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ATTLIST multi-pattern-scan
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
>
<!ATTLIST pattern
accession CDATA #REQUIRED
name CDATA #REQUIRED
pvalue CDATA #IMPLIED
score CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST scanned-sequence
accession CDATA #REQUIRED
name CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
length CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST matched-element
start CDATA #REQUIRED
stop CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
clusterid CDATA #IMPLIED
>

]>
<cis-element-search
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://zlab.bu.edu/schema/cisml cisml.xsd"
  xmlns="http://zlab.bu.edu/schema/cisml"
  xmlns:mem="http://noble.gs.washington.edu/meme"
>
<program-name>fimo</program-name>
<parameters>
<command-line>fimo --parse-genomic-coord --verbosity 1 --oc /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/fimo_out_4 --bgfile /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/background --motif 2-RRCCAATSRGMR /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/streme_out/streme.xml /ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/human_promoter.fa</command-line>
<pattern-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/streme_out/streme.xml</pattern-file>
<sequence-file>/ocean/projects/bio230007p/sujathab/Motif_analysis/output/meme_chip_human_promoter/human_promoter.fa</sequence-file>
<site-pvalue-cutoff>0.0001</site-pvalue-cutoff>
<sequence-filtering on-off="off"/>
</parameters>
<pattern accession="2-RRCCAATSRGMR" name="STREME-2">
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="16657092" stop="16657103" score="16.2838" pvalue="2.05e-06">
<sequence>AACCAATGAGAT</sequence>
<mem:qvalue>0.0437</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="20820345" stop="20820334" score="16.8784" pvalue="1.14e-06">
<sequence>AGCCAATCATAA</sequence>
<mem:qvalue>0.0336</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="20921265" stop="20921276" score="10.6486" pvalue="5.8e-05">
<sequence>AGCCAATAGCTT</sequence>
<mem:qvalue>0.24</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="30949736" stop="30949747" score="10.9324" pvalue="5.25e-05">
<sequence>AGCCAATGCGCG</sequence>
<mem:qvalue>0.226</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="34459738" stop="34459727" score="13.7568" pvalue="1.49e-05">
<sequence>AGCCAATGAAGA</sequence>
<mem:qvalue>0.116</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="36445289" stop="36445278" score="10.9459" pvalue="5.21e-05">
<sequence>GGCCAATGGGTT</sequence>
<mem:qvalue>0.226</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="37029280" stop="37029269" score="10.7027" pvalue="5.59e-05">
<sequence>CGCCAATCACAG</sequence>
<mem:qvalue>0.234</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="39340924" stop="39340913" score="14.3784" pvalue="1.05e-05">
<sequence>AGCCAATCAAGG</sequence>
<mem:qvalue>0.0954</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="42851144" stop="42851155" score="12.2838" pvalue="3.16e-05">
<sequence>ACCCAATCAGCG</sequence>
<mem:qvalue>0.171</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="43933936" stop="43933925" score="12.0676" pvalue="3.37e-05">
<sequence>AGCCAATCATAC</sequence>
<mem:qvalue>0.177</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="51478567" stop="51478578" score="9.52703" pvalue="8.14e-05">
<sequence>GACCAATGGTCT</sequence>
<mem:qvalue>0.292</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="52119428" stop="52119417" score="17.1486" pvalue="9.54e-07">
<sequence>AGCCAATCAGCG</sequence>
<mem:qvalue>0.0314</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="53297056" stop="53297067" score="14.6757" pvalue="8.09e-06">
<sequence>AGCCAATCGGCT</sequence>
<mem:qvalue>0.0813</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="55052788" stop="55052777" score="10.2027" pvalue="6.56e-05">
<sequence>AGCCAATCCGGG</sequence>
<mem:qvalue>0.255</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="59237396" stop="59237407" score="8.93243" pvalue="9.65e-05">
<sequence>AACCAATCGTCC</sequence>
<mem:qvalue>0.323</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="59481989" stop="59482000" score="13.0541" pvalue="2.16e-05">
<sequence>ACCCAATCGGAA</sequence>
<mem:qvalue>0.139</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="66671650" stop="66671661" score="15.2703" pvalue="5.18e-06">
<sequence>AGCCAATCATAT</sequence>
<mem:qvalue>0.0647</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="69689187" stop="69689176" score="14.6622" pvalue="8.52e-06">
<sequence>AACCAATGGCAG</sequence>
<mem:qvalue>0.0842</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="71653315" stop="71653304" score="13.027" pvalue="2.25e-05">
<sequence>GGCCAATAGGCG</sequence>
<mem:qvalue>0.141</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="74284763" stop="74284774" score="10.3243" pvalue="6.3e-05">
<sequence>GGCCAATGGCGA</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="74854815" stop="74854804" score="14.7703" pvalue="7.68e-06">
<sequence>AACCAATAGGAT</sequence>
<mem:qvalue>0.0804</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="82293053" stop="82293042" score="10.7973" pvalue="5.44e-05">
<sequence>CACCAATCAGCA</sequence>
<mem:qvalue>0.231</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
<matched-element start="84751549" stop="84751538" score="11.7432" pvalue="3.82e-05">
<sequence>ATCCAATAATAG</sequence>
<mem:qvalue>0.187</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>
<scanned-sequence accession="chr1" name="chr1">
</scanned-sequence>